/gcar/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # Joint State Broadcaster (publishes joint states)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # Arm Joint Trajectory Controller
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/gcar/arm_controller:
  ros__parameters:
    joints:
      - arm_base_joint
      - shoulder_joint
      - elbow_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      
      arm_base_joint:
        trajectory: 0.05
        goal: 0.02
      
      shoulder_joint:
        trajectory: 0.05
        goal: 0.02
      
      elbow_joint:
        trajectory: 0.05
        goal: 0.02

/gcar/joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

